name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-lastest
    starategy:
      matrix:
        node-version: [16.x]
    seeps:
      - users: actions/sheckout@v2
      - users: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm yaspeller